##########################
# Proxmox 백업USB 마운트 
##########################
USB_MOUNT="usb-bakcup"

##########################
# Proxmox Disk Partition 라벨
##########################
MAIN="main"
DATA="data"
DIR_NAME="directory"

##########################
# Proxmox Ubuntu
##########################
CT_ID="101"
HOSTNAME="Ubuntu"
MEMORY_GB="18"
ROOTFS="128"
CORES="6"
CPU_LIMIT="6"
UNPRIVILEGED="0"
RCLONE_GB="256"
LV_RCLONE="lv-rclone"
LOCALE_LANG="ko_KR.UTF-8"
TIMEZONE="Asia/Seoul"
DOCKER_DATA_ROOT="/docker/core"
DOCKER_DNS1="8.8.8.8"
DOCKER_DNS2="1.1.1.1"
DOCKER_BRIDGE_NET="172.18.0.0/24"
DOCKER_BRIDGE_GW="172.18.0.1"
BASIC_APT="curl wget htop tree neofetch git vim net-tools nfs-common"
ALLOW_PORTS="80/tcp 443/tcp 443/udp 45876 5574 9999 32400"
